Issue 90
PhenoApps/Intercross pull request #99
Opened 2024-10-27 17:59 UTC by romil2807

All the changes are implemented except for:

1. Person settings to match as Fieldbook 
2. Top toolbar in About page

2024-11-16 09:06 UTC, trife requested changes
- [ ] Main settings page top toolbar is missing
- [ ] Person dialog doesn't open
- [ ] Create cross ID pattern toolbar has a white gap above it, the text is black instead of matching the other toolbar text, and it says Intercross instead of "Cross ID Pattern"

2024-11-27 19:27 UTC, trife approved these changes

2024-12-17 16:43 UTC, chaneylc requested changes
Is there a reason FieldBook's GeneralKeys replace all of the KeyUtil code? 

I think it's best if you replace GeneralKeys with my original KeyUtil code, if you're adding a key you need to add it to keys.xml and then reference that string id in the KeyUtil, which is essentially GeneralKeys without having to type the key twice.

2024-12-18 21:29 UTC, chaneylc approved these changes

2025-01-03 20:26 UTC, merged